spring:
  datasource:
    url: jdbc:h2:mem:bonddb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple

server:
  port: 8080
